### ISSUE TITLE
Force Furnace breaks instantly, incorrect drops

### ISSUE THREAD

**Issue by nyuppo** [BURN447/DartcraftReloaded#11]
When breaking a force furnace, it breaks instantly. If you use a fist then it drops nothing, and if you use a pickaxe it drops a normal furnace.

[forcefurnace bug 01.zip](https://github.com/BURN447/DartcraftReloaded/files/2720999/forcefurnace.bug.01.zip)

**Comment by BURN447** [comment]
Fixed in Commit fe5b2b71f10d795cc8cc4f6a8909e0c9ad68db67
