### ISSUE TITLE
Force Logs sound like stone, should sound like wood

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#18]
When breaking or walking on a force log, it plays the same sound as a block of stone would, instead of the noise that is played when one walks on an oak log or oak plank.

Using version 1.12.2-2.1.2-Beta, with forge version 14.23.5.2797

**Comment by BURN447** [comment]
Fixed in commit 853565c29cc397717d95e51b77041be08015bb41
