### ISSUE TITLE
Idea: Utilize the Projects tab to keep track of issues and of what needs to get done

### ISSUE THREAD

**Issue by OverloadedWolf** [BURN447/DartcraftReloaded#2]
Hi, I am looking to help in the development. But don't really know what's being worked on and by who. Would it benefit you to use the Projects tab to keep track of currently worked on modules so there isn't any overlap?

**Comment by BURN447** [comment]
Currently I am using Gitkraken's Glo tracker, but I may restructure onto the Projects Tab here in the near future. I'm going to close this issue, but I highly implore you to take a look into anything you see that needs attention in the meantime. Feel free to submit pull requests and I'll take a look.

**Comment by OverloadedWolf** [comment]
Will do, I'm coming back from a hiatus on modding and gotta refresh myself on setting up an existing project. Had some issues. Any quick advice, apologies for asking.
