### ISSUE TITLE
Force Logs cannot be placed horizontally.

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#20]
Apologies for the issue spam, I've been excited to try this for a while and thought I'd get the clear stuff out of the way first.

Anyway, force logs do not rotate horizontally when placed.
[Shown in Video](https://cdn.unascribed.com/sleepingtown/media_attachments/files/001/071/844/original/0e14d73cd1f0a4c0.mp4)

**Comment by BURN447** [comment]
Fixed in Commit 853565c29cc397717d95e51b77041be08015bb41
