### ISSUE TITLE
Force Wrenches can stack greater than 1.

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#21]
Force Wrenches can currently stack up to 64, assuming this is unintentional.
![image](https://user-images.githubusercontent.com/20749209/50661214-65c9f980-0f70-11e9-8738-7d64cf9ef1c3.png)

Using version 1.12.2-2.1.2-Beta, with forge version 14.23.5.2797

**Comment by BURN447** [comment]
Fixed with Commit 6b787dcd8084dcbd3f7e4a5f4d0813bf61f65ee1
