### ISSUE TITLE
New Force Nugget texture is slightly off-center.

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#22]
As shown here:
![image](https://user-images.githubusercontent.com/20749209/50662735-6fa22b80-0f75-11e9-9b63-87f9e71c86b8.png)

Using version 1.12.2-2.1.2-Beta, with forge version 14.23.5.2797

**Comment by BURN447** [comment]
Given to the texture artists. Should be fixed soon

**Comment by BURN447** [comment]
Fixed with Commit 0197117dbde55bfd21a5146272822df013413b04
