### ISSUE TITLE
Force Trees still spawn in superflat worlds.

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#23]
![image](https://user-images.githubusercontent.com/20749209/50663420-92cdda80-0f77-11e9-9e7f-e71694c1c217.png)
version 1.12.2-2.1.2-Beta, forge version 14.23.5.2797

**Comment by BURN447** [comment]
Fixed in commit f6cc927ff2fc755f69eb2c03ac4724834916753e
