### ISSUE TITLE
Force axe does not mine force logs/wood at proper speed

### ISSUE THREAD

**Issue by nyuppo** [BURN447/DartcraftReloaded#26]
The force axe mines other log types quickly as it should, but when mining force logs/wood it mines at the speed of a fist.

[force axe bug 01.zip](https://github.com/BURN447/DartcraftReloaded/files/2726035/force.axe.bug.01.zip)

**Comment by BURN447** [comment]
Fixed with Commit bb43583a3ae530427fd7f8cb5156c83658ed1a9f
