### ISSUE TITLE
Crashes on dedicated server.

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#27]
https://gist.github.com/Birgliss/b4ef022d5cfab60106f2e7eac5a382c1

modlist outlined [here](https://kat.blue/millenia.html)

**Comment by BURN447** [comment]
Fixed in Commit 201318282f3e0af5e2eaa87a1994a24219c5012e

Please provide more information the next time you submit a bug report. Without extra information it can be extremely hard to diagnose and reproduce a bug

**Comment by Birgliss** [comment]
ah, alright, my bad. will do.
