### ISSUE TITLE
are force logs inheriting BlockLog properly?

### ISSUE THREAD

**Issue by Birgliss** [BURN447/DartcraftReloaded#28]
i've noticed a lot of issues involving the force logs, maybe it just needs to extend the BlockLog class?

**Comment by BURN447** [comment]
Originally I was using a custom block base, but they are going to with some work in the next updates. I have to change around a bunch of code before that will work.

**Comment by BURN447** [comment]
Fixed in Commit d6adf755bd7a3d1d1c17407df4e853018b586355
