### ISSUE TITLE
Crash when breaking "Sand below Sand"

### ISSUE THREAD

**Issue by Lordmau5** [BURN447/DartcraftReloaded#3]
**Describe the bug**
When having 2 Sand blocks above each other and the bottom one is broken, the top one is changed into a `EntityFallingBlock` and falls down. Basic Vanilla mechanic.
However, instead of it dropping as it should, a crash is thrown.
In my testing, it could reproduce it most of the time.

**To Reproduce**
1. Place 2 Sand blocks above each other
2. Break bottom Sand block
3. Crash should happen

**Expected behavior**
It... shouldn't crash

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DartCraft Reloaded Version: 1.0.0-Beta
 - Forge Version: 14.23.5.2796

**Additional context**
N/A

**Proposed solution**
To not blindly assume that the `event.getTarget()` result in [attackEntityEvent](https://github.com/BURN447/DartcraftReloaded/blob/master/src/main/java/burn447/dartcraftReloaded/Events/attackEntityEvent.java#L54) is always an instance of `EntityLivingBase`

**Comment by BURN447** [comment]
I have not been able to reproduce this crash. However, I have changed the code to reflect your proposed solution and it now checks to see if the target is an instance of EntityLivingBase before applying the effect. Can you post a video of what you were doing, as well as what tool you were using with what exact modifers.

**Comment by Lordmau5** [comment]
I wasn't using any tool for this. It was just with bare hands, but even with a tool it shouldn't make a difference seeing as it wouldn't change how the affected line would behave.

So I've tried reproducing this in a Singleplayer world, and it doesn't crash outright - but it surely throws that same error in the console.
https://paste.gg/p/anonymous/421213afecb34434b5b21aa955ca8af4

However, the actual full crash happened when I was playing on a dedicated server.
The server continued to run fine, but when I tried to break the Sand it crashed my client and I got disconnected (VanillaFix helped in not causing my game to crash as a whole).

I wanted to quickly spin up a dedicated server locally on Windows, and it caused this crash upon launch:
https://paste.gg/p/anonymous/77a421178e784fa6a350b0e83aa54ada
Which is because of a typo in the [`dartcraftReloaded`](https://github.com/BURN447/DartcraftReloaded/blob/master/src/main/java/burn447/dartcraftReloaded/dartcraftReloaded.java#L44) file (instead of `dartcraftReloaded` you wrote `dartcraftreloaded` and apparently Windows can't compensate for that?)

After I got the dedicated server running locally, I joined and spawned right next to some Sand, perfect for some testing.
And here you have your a video showing what I was doing:

[Singleplayer World](https://streamable.com/meiwy), no crashes, just errors in the console as I mentioned
[Multiplayer World / Dedicated Server](https://streamable.com/xg556), immediate crash

I'd actually suggest trying out your mod on a dedicated server, too. Gradle should've set up both a `Minecraft Client` and `Minecraft Server` launch profile for testing.

**Comment by BURN447** [comment]
I cannot test on windows for another week, but as of now, I have not been able to reproduce this bug. As such, I am deciding to close this issue unless I can get another account of it happening from another user. However, I have fixed the typo about the server proxy in Commit 8c71691457e307d045ee618d3b29a0025d868ad3
