### ISSUE TITLE
Force tree sapling has incorrect sounds

### ISSUE THREAD

**Issue by nyuppo** [BURN447/DartcraftReloaded#34]
The force tree sapling plays stone sounds when breaking and placing.

[force sapling bug 01.zip](https://github.com/BURN447/DartcraftReloaded/files/2826491/force.sapling.bug.01.zip)

**Comment by BURN447** [comment]
Fixed with Commit 8b8ab5489be8e3fd4329a66a253e406a202c8797

**Comment by Retr0gue** [comment]
The force logs also have the incorrect sound with the most recent release (out for only 4 days now)
