### ISSUE TITLE
Grinding doesn't work on Force Pickaxe, Neither does Lumberjack on an Axe

### ISSUE THREAD

**Issue by Findonovan95** [BURN447/DartcraftReloaded#35]
I tried using flint to add the grinding attribute to a pickaxe but the grinding attribute just disappears when i try to mine some ore. Tried with a couple different ores. Tried using more and less flint. It just doesn't seem to work. Sorry if this is a known issue :) Also Lumberjack for an Axe doesn't seem to work either. I got it working once but then it stopped and I don't know how I got it working or why it stopped.

**Comment by BURN447** [comment]
The Lumberjack part was because I forgot a block check in the lumberjack code.

Lumberjack fixed in commit 03bad90fe8c843f2aca742e531e43545a08ced44
