### ISSUE TITLE
Force Planks not being crafted into force sticks

### ISSUE THREAD

**Issue by CauseKey** [BURN447/DartcraftReloaded#36]
**Describe the bug**
Trying to craft force sticks in a regular crafting table the force planks wood turn into regular sticks
**To Reproduce**

**Expected behavior**
The crafting of force sticks
**Screenshots**
http://prntscr.com/mij2dt
**Desktop (please complete the following information):**
 - OS: [e.g.Windows 10]
Windows 10
**Additional context**
I am using no other mods apart from DCR on the twitch launcher, this bug makes DCR imposible to be used in survival

**Comment by BURN447** [comment]
Fixed with commit 548d2b432ad37262891316427d3adbb02673bbe8
