### ISSUE TITLE
[Suggestion] Force Engines for BuildCraft interoperability

### ISSUE THREAD

**Issue by gdm413229** [BURN447/DartcraftReloaded#38]
The original mod had the force engine for generating Minecraft Joules, which is a unit of energy added by BuildCraft.  The force engine is along the same tier [power output wise] as BuildCraft's combustion engine but without the explosions from highly flammable fuels igniting in the fuel tank and fuel pipes.  When this engine overheats, it gets seized up [can't generate any more power] and has to be repaired with the Force Wrench.

The force engine runs on liquid fuels and uses a secondary fluid as a "throttle" fluid, sorta like the engine's coolant.  Running the engine with only liquid force gives a 1x power multiplier and only outputs 4 MJ per tick.  Burning oil/dense oil in the engine yields residue due to the oil refining overhaul in BuildCraft since MC 1.11!

These tables below are sample values taken from Dartcraft's documentation in the web, some values are absent and are represented as a question mark.

### Sample List of Fuels and their Figures

Fuel  | MJ/tick | Ticks per bucket | Total power [MJ]
-------|----------|----------------------|----------------------
Lava | 0.5 | 20000 | 10000
Creosote [Immersive Engineering or Railcraft] | 1.25 | 15000 | ?
Oil (Cool) | 1.5 | 20000 | 30000
Dense Oil (Cool) | 2 | 27500 | ?
Biofuel | 2 | 60000 | 120000
Gaseous Fuel (Cool) | 2.75 | 87500 | ?
Fuel (Cool) | 3 | 100000 | 300000
Liquid Force | 4 | 10000 | 40000

### Sample Throttle Fluid [Coolant] Values

Throttle Fluid | MJ Multiplier | Buckets / 250mB Liquid Force | MJ / 250mB Liquid Force
-----------------|-----------------|----------------------------------------|--------------------------------
Empty Tank | 1.0x | N/A | 40000
Water | 2.0x | 10 | 80000
Milk | 2.5x | 3.333 | 100000
Crushed Ice [requires Forestry mod], IC2 Coolant | 4 | 0.5 | ~100000
Gelid Cryotheum [requires Thermal Expansion] | 8 | 0.25 | ~20000
Liquid Nitrogen [requires NuclearCraft] | 16 | 0.25 | ?
Liquid Helium [requires NuclearCraft] | 32 | 0.125 | ?
```
CRAFTING RECIPE FOR FORCE ENGINE

LEGEND: G = GLASS
P = PISTON
I = FORCE INGOT
M = FORCE GEAR
. = EMPTY SLOT

III
.G.
MPM
```

**Comment by BURN447** [comment]
The Force Engine is planned to be implemented at a later date. As of now, there's no Energy support in the mod. However, there wil be a force Engine, Force Dynamo and Support for Fluid Force in other mods power generation.

**Comment by gdm413229** [comment]
Any plans for a Force Generator that works like the Force Engine?  The Force Generator outputs power for the IC2 energy net.

**Comment by BURN447** [comment]
That's still on the fence. I may just add functionality to the IC2 Semi-Fluid Generator instead

**Comment by gdm413229** [comment]
Any word of a Mekanism-type generator running on Liquid Force???

**Comment by BURN447** [comment]
That's a possibility. Unfortunately, there are two forks of mekanism out there right now, and nobody can choose one to use over the other. I would prefer not to have to support both versions of the mod, but there is always a possibility

**Comment by gdm413229** [comment]
Any plans for a generator for GregTech Community Edition being fueled by liquid Force???  Could be useful if you don't want to use NuclearCraft batteries as energy bridges between IC2 cables and GTCE cables.

**Comment by BURN447** [comment]
Lots of the power system is still to be flushed out. I don't want a ton of generators in the mod, just because that is not the primary focus. Lots of these would be more suited to an addon mod than the base mod.
