### ISSUE TITLE
Putting GPS in offhand and main hand pulls up 2 ui helpers

### ISSUE THREAD

**Issue by nyuppo** [BURN447/DartcraftReloaded#39]
When you hold a golden power source a little ui helper tells you how much you have in your inventory. However when you hold one in your offhand and your main hand, it pulls up 2 helpers.

[gps helper bug.zip](https://github.com/BURN447/DartcraftReloaded/files/3010474/gps.helper.bug.zip)

**Comment by BURN447** [comment]
I'm honestly not sure what could be causing this issue. Gorge and Vanilla handle this stuff, so this one is going to be closed for the time being.
