### ISSUE TITLE
Soul wafer gives 2 status effects

### ISSUE THREAD

**Issue by nyuppo** [BURN447/DartcraftReloaded#7]
After consuming a soul wafer, the player receives 2 status effects rather than the intended 1.

**Comment by callousCelebration** [comment]
The second one notable does not clear when using /effect @p clear, and after using the command the effect does not stop being in effect until a relog. Untested with milk

**Comment by BURN447** [comment]
Fixed with Commit 7a268222c9bd65978e864f0e61e87928327f1b8c

Had an issue where it was applying the effect on both sides and there is no need to apply it on more than one. Fixed with a simple world.isRemote check
